const WORLD_SIZE = 3000;

const AMMO = {
  round: {
    name: 'Round Shot',
    hullDmg: 35,
    sailDmg: 8,
    crewDmg: 12,
    speed: 23,
    spread: 0.04,
    pellets: 1,
    color: '#1a1a1a',
    glow: '#ffaa00',
    trail: '#ffcc44',
  },
  chain: {
    name: 'Chain Shot',
    hullDmg: 14,
    sailDmg: 45,
    crewDmg: 18,
    speed: 21,
    spread: 0.07,
    pellets: 2,
    color: '#8b6914',
    glow: '#ffd700',
    trail: '#ffe066',
    slowFactor: 0.5,
    slowDuration: 4000,
  },
  grape: {
    name: 'Grapeshot',
    hullDmg: 10,
    sailDmg: 12,
    crewDmg: 55,
    speed: 19,
    spread: 0.17,
    pellets: 6,
    color: '#5c3a1e',
    glow: '#ff8844',
    trail: '#ffaa66',
  },
};

const GUNS = [
  {
    id: 0,
    name: 'Iron Swivel Chasers',
    price: 0,
    desc: 'Light dual bow swivels. Reliable fire rate and precision aiming.',
    damage: 1.0,
    reload: 750,
    range: 620,
    spreadMod: 0.9,
    color: '#94a3b8',
    volley: 2,
    bulletType: 'iron',
    cursorStyle: 'swivel',
    icon: '⚙',
    ammoModes: [
      {
        id: 'swivel_standard',
        name: 'Twin Solid Shot',
        shortName: 'Twin Shot [1]',
        icon: '●',
        typeTag: 'BALANCED',
        badgeClass: 'tag-balanced',
        pellets: 1,
        spread: 0.04,
        speed: 24,
        hullDmg: 35,
        sailDmg: 12,
        crewDmg: 15,
        color: '#94a3b8',
        glow: '#cbd5e1',
        pierce: 0,
        special: 'standard',
        desc: 'Rapid twin iron shot delivering steady harassment.',
      },
      {
        id: 'swivel_canister',
        name: 'Canister Shotgun',
        shortName: 'Canister [2]',
        icon: '💥',
        typeTag: 'SHOTGUN',
        badgeClass: 'tag-shotgun',
        pellets: 8,
        spread: 0.28,
        speed: 19,
        range: 280,
        hullDmg: 16,
        sailDmg: 32,
        crewDmg: 42,
        color: '#e2e8f0',
        glow: '#f59e0b',
        pierce: 0,
        special: 'shotgun',
        desc: 'Close-quarters shotgun blast of 8 shrapnel balls that shreds hulls and sails at point-blank range.',
      },
      {
        id: 'swivel_pierce',
        name: 'Piercing Iron Dart',
        shortName: 'Pierce Bolt [3]',
        icon: '⚡',
        typeTag: 'PIERCING',
        badgeClass: 'tag-piercing',
        pellets: 1,
        spread: 0.015,
        speed: 31,
        hullDmg: 72,
        sailDmg: 20,
        crewDmg: 25,
        color: '#64748b',
        glow: '#38bdf8',
        pierce: 3,
        special: 'pierce',
        desc: 'Single forged heavy iron dart that pierces through up to 3 enemy ships in a line!',
      },
    ],
  },
  {
    id: 1,
    name: 'Bronze 12-Pounder',
    price: 800,
    desc: 'Heavy cast bronze naval cannons delivering punishing 3-ball volleys.',
    damage: 1.4,
    reload: 700,
    range: 720,
    spreadMod: 0.8,
    color: '#cd7f32',
    volley: 3,
    bulletType: 'bronze',
    cursorStyle: 'naval',
    icon: '⚓',
    ammoModes: [
      {
        id: 'bronze_heavy',
        name: 'Heavy Broad-Ball',
        shortName: 'Broad-Ball [1]',
        icon: '●',
        typeTag: 'HEAVY',
        badgeClass: 'tag-heavy',
        pellets: 1,
        spread: 0.04,
        speed: 23,
        hullDmg: 48,
        sailDmg: 15,
        crewDmg: 18,
        color: '#cd7f32',
        glow: '#d97706',
        pierce: 0,
        special: 'standard',
        desc: 'Thunderous cast bronze round ball with crushing kinetic impact.',
      },
      {
        id: 'bronze_scrap',
        name: 'Lead-Scrap Blunder',
        shortName: 'Scrap-Gun [2]',
        icon: '💥',
        typeTag: 'SHOTGUN',
        badgeClass: 'tag-shotgun',
        pellets: 9,
        spread: 0.30,
        speed: 18,
        range: 290,
        hullDmg: 20,
        sailDmg: 36,
        crewDmg: 48,
        color: '#b45309',
        glow: '#f59e0b',
        pierce: 0,
        special: 'shotgun',
        desc: 'Deadly point-blank shotgun blast of 9 jagged bronze scrap pieces with massive close-range stopping power.',
      },
      {
        id: 'bronze_chain',
        name: 'Dismantling Bar-Shot',
        shortName: 'Bar-Shot [3]',
        icon: '⛓',
        typeTag: 'CRIPPLING PIERCE',
        badgeClass: 'tag-crippling',
        pellets: 1,
        spread: 0.02,
        speed: 24,
        hullDmg: 48,
        sailDmg: 75,
        crewDmg: 30,
        color: '#f59e0b',
        glow: '#fbbf24',
        pierce: 3,
        slowDuration: 3500,
        special: 'pierce',
        desc: 'Revolving iron bar that pierces clean through up to 3 enemy ships, stripping sails and slowing them.',
      },
    ],
  },
  {
    id: 2,
    name: 'Long Nine "Sniper Chaser"',
    price: 1800,
    desc: 'Precision long-barrel cannon with extreme range and piercing projectile speed.',
    damage: 2.2,
    reload: 620,
    range: 960,
    spreadMod: 0.35,
    color: '#38bdf8',
    volley: 2,
    bulletType: 'sniper',
    cursorStyle: 'sniper',
    icon: '🎯',
    ammoModes: [
      {
        id: 'sniper_pierce',
        name: 'Hyper-Velocity Dart',
        shortName: 'Rail Dart [1]',
        icon: '⚡',
        typeTag: 'HYPER-PIERCE',
        badgeClass: 'tag-piercing',
        pellets: 1,
        spread: 0.01,
        speed: 38,
        hullDmg: 85,
        sailDmg: 28,
        crewDmg: 30,
        color: '#38bdf8',
        glow: '#0284c7',
        pierce: 4,
        special: 'pierce',
        desc: 'Single hyper-velocity rail dart that punches straight through up to 4 enemy hulls in a line!',
      },
      {
        id: 'sniper_flechette',
        name: 'Flechette Needle-Gun',
        shortName: 'Flechette [2]',
        icon: '💥',
        typeTag: 'SHOTGUN',
        badgeClass: 'tag-shotgun',
        pellets: 6,
        spread: 0.16,
        speed: 28,
        range: 310,
        hullDmg: 28,
        sailDmg: 34,
        crewDmg: 40,
        color: '#7dd3fc',
        glow: '#38bdf8',
        pierce: 0,
        special: 'shotgun',
        desc: 'High-speed close-range shotgun blast of 6 needle-sharp steel flechettes delivering tight lethal bursts.',
      },
      {
        id: 'sniper_slug',
        name: 'Keel-Cracking Slug',
        shortName: 'Keel Slug [3]',
        icon: '🎯',
        typeTag: 'CRITICAL',
        badgeClass: 'tag-critical',
        pellets: 1,
        spread: 0.01,
        speed: 33,
        hullDmg: 105,
        sailDmg: 16,
        crewDmg: 26,
        color: '#0284c7',
        glow: '#38bdf8',
        pierce: 0,
        special: 'critical',
        desc: 'Precision heavy slug calibrated for devastating critical hull penetration.',
      },
    ],
  },
  {
    id: 3,
    name: 'Carronade "Smasher"',
    price: 3200,
    desc: 'Massive short-bore gun that unleashes a lethal 5-cannonball spread.',
    damage: 2.0,
    reload: 520,
    range: 600,
    spreadMod: 1.1,
    color: '#e2e8f0',
    volley: 5,
    bulletType: 'smasher',
    cursorStyle: 'heavy',
    icon: '💥',
    ammoModes: [
      {
        id: 'smasher_buckshot',
        name: 'Gargantuan Buckshot',
        shortName: 'Buckshot [1]',
        icon: '💥',
        typeTag: 'HEAVY SHOTGUN',
        badgeClass: 'tag-shotgun',
        pellets: 12,
        spread: 0.32,
        speed: 19,
        range: 280,
        hullDmg: 24,
        sailDmg: 40,
        crewDmg: 55,
        color: '#e2e8f0',
        glow: '#94a3b8',
        pierce: 0,
        special: 'shotgun',
        desc: 'The ultimate naval blunderbuss! Fires 12 heavy lead balls that pulverize ships at point-blank range.',
      },
      {
        id: 'smasher_ram',
        name: 'Siege Ram Slug',
        shortName: 'Siege Slug [2]',
        icon: '🛡️',
        typeTag: 'HEAVY PIERCE',
        badgeClass: 'tag-piercing',
        pellets: 1,
        spread: 0.015,
        speed: 26,
        hullDmg: 110,
        sailDmg: 25,
        crewDmg: 30,
        color: '#475569',
        glow: '#cbd5e1',
        pierce: 4,
        special: 'pierce',
        desc: 'Single colossal iron slug that crushes and pierces through up to 4 vessels, tearing massive breaches.',
      },
      {
        id: 'smasher_scatter',
        name: 'Deck-Sweeper Shrapnel',
        shortName: 'Scatter [3]',
        icon: '✦',
        typeTag: 'SCATTER SHOTGUN',
        badgeClass: 'tag-scatter',
        pellets: 16,
        spread: 0.38,
        speed: 17,
        range: 260,
        hullDmg: 16,
        sailDmg: 46,
        crewDmg: 68,
        color: '#64748b',
        glow: '#f59e0b',
        pierce: 0,
        special: 'shotgun',
        desc: 'Wide-angle close-range storm of 16 hot shrapnel pellets wiping out sails and enemy crews.',
      },
    ],
  },
  {
    id: 4,
    name: 'Volcanic Magma Mortar',
    price: 5000,
    desc: 'Fires molten volcanic projectiles that scorch target hulls with explosive shockwaves.',
    damage: 3.2,
    reload: 460,
    range: 860,
    spreadMod: 0.55,
    color: '#f97316',
    volley: 3,
    bulletType: 'magma',
    cursorStyle: 'mortar',
    icon: '🌋',
    ammoModes: [
      {
        id: 'mortar_core',
        name: 'Molten Core Bomb',
        shortName: 'Magma Bomb [1]',
        icon: '🌋',
        typeTag: 'AOE MORTAR',
        badgeClass: 'tag-mortar',
        pellets: 1,
        spread: 0.05,
        speed: 18,
        hullDmg: 82,
        sailDmg: 30,
        crewDmg: 30,
        color: '#ea580c',
        glow: '#f97316',
        aoeRadius: 95,
        special: 'mortar',
        desc: 'High-arc volcanic bomb that causes an explosive 95px AOE shockwave on impact.',
      },
      {
        id: 'mortar_cluster',
        name: 'Magma Cluster Blast',
        shortName: 'Cluster [2]',
        icon: '💥',
        typeTag: 'SHOTGUN MORTAR',
        badgeClass: 'tag-shotgun',
        pellets: 7,
        spread: 0.26,
        speed: 18,
        range: 310,
        hullDmg: 32,
        sailDmg: 30,
        crewDmg: 36,
        color: '#f97316',
        glow: '#fb923c',
        aoeRadius: 40,
        special: 'shotgun',
        desc: 'Close-quarters shotgun mortar burst of 7 burning lava bomblets with miniature splash explosions.',
      },
      {
        id: 'mortar_drill',
        name: 'Obsidian Drill Lance',
        shortName: 'Drill Lance [3]',
        icon: '⚡',
        typeTag: 'MOLTEN PIERCE',
        badgeClass: 'tag-piercing',
        pellets: 1,
        spread: 0.015,
        speed: 28,
        hullDmg: 135,
        sailDmg: 30,
        crewDmg: 35,
        color: '#c2410c',
        glow: '#ea580c',
        pierce: 4,
        special: 'pierce',
        desc: 'Single superheated obsidian lance that burns and pierces straight through up to 4 enemy hulls.',
      },
    ],
  },
  {
    id: 5,
    name: 'Kraken\'s Abyssal Tormentor',
    price: 7500,
    desc: 'Harnesses dark abyssal sorcery to fire seeking vortexes that slow and crush enemy ships.',
    damage: 4.2,
    reload: 400,
    range: 900,
    spreadMod: 0.45,
    color: '#a855f7',
    volley: 4,
    bulletType: 'kraken',
    cursorStyle: 'eldritch',
    icon: '🐙',
    ammoModes: [
      {
        id: 'kraken_vortex',
        name: 'Abyssal Void Orb',
        shortName: 'Void Orb [1]',
        icon: '🐙',
        typeTag: 'HOMING',
        badgeClass: 'tag-homing',
        pellets: 1,
        spread: 0.03,
        speed: 20,
        hullDmg: 88,
        sailDmg: 35,
        crewDmg: 35,
        color: '#9333ea',
        glow: '#c084fc',
        slowDuration: 4000,
        special: 'homing',
        desc: 'Homing dark vortex that curves towards nearby enemy ships, crushing hulls and slowing by 60%.',
      },
      {
        id: 'kraken_tendril',
        name: 'Soul-Siphon Tendrils',
        shortName: 'Siphon [2]',
        icon: '🩸',
        typeTag: 'LIFE-STEAL SHOTGUN',
        badgeClass: 'tag-shotgun',
        pellets: 8,
        spread: 0.24,
        speed: 19,
        range: 290,
        hullDmg: 26,
        sailDmg: 28,
        crewDmg: 38,
        color: '#a855f7',
        glow: '#e9d5ff',
        lifeSteal: true,
        special: 'shotgun',
        desc: 'Close-quarters shotgun blast of 8 shadowy tentacles that heals your ship for 18% of damage dealt!',
      },
      {
        id: 'kraken_lance',
        name: 'Dark-Matter Lance',
        shortName: 'Void Lance [3]',
        icon: '⚡',
        typeTag: 'VOID PIERCE',
        badgeClass: 'tag-piercing',
        pellets: 1,
        spread: 0.01,
        speed: 32,
        hullDmg: 155,
        sailDmg: 45,
        crewDmg: 45,
        color: '#7e22ce',
        glow: '#c084fc',
        pierce: 5,
        special: 'pierce',
        desc: 'Single infinite eldritch beam that pierces through up to 5 ships with reality-warping void power.',
      },
    ],
  },
  {
    id: 6,
    name: 'Poseidon\'s Tempest Arc',
    price: 11000,
    desc: 'Electrified celestial harpoons crackling with chain lightning that electrocutes the sea!',
    damage: 5.8,
    reload: 340,
    range: 1020,
    spreadMod: 0.38,
    color: '#06b6d4',
    volley: 4,
    bulletType: 'lightning',
    cursorStyle: 'storm',
    icon: '⚡',
    ammoModes: [
      {
        id: 'tempest_chain',
        name: 'Chain Lightning Harpoon',
        shortName: 'Chain Arc [1]',
        icon: '⚡',
        typeTag: 'CHAIN LIGHTNING',
        badgeClass: 'tag-chain',
        pellets: 1,
        spread: 0.02,
        speed: 29,
        hullDmg: 98,
        sailDmg: 40,
        crewDmg: 40,
        color: '#06b6d4',
        glow: '#22d3ee',
        chainLightning: true,
        special: 'chain',
        desc: 'Celestial electric spear that arcs chain lightning to up to 3 nearby ships on impact!',
      },
      {
        id: 'tempest_shotgun',
        name: 'Storm Cloud Shotgun',
        shortName: 'Storm Arc [2]',
        icon: '💥',
        typeTag: 'ELECTRIC SHOTGUN',
        badgeClass: 'tag-shotgun',
        pellets: 9,
        spread: 0.28,
        speed: 21,
        range: 300,
        hullDmg: 30,
        sailDmg: 38,
        crewDmg: 48,
        color: '#22d3ee',
        glow: '#67e8f9',
        slowDuration: 2500,
        special: 'shotgun',
        desc: 'Close-range electric shotgun discharging 9 crackling storm sparks in a cone that paralyze enemies.',
      },
      {
        id: 'tempest_pierce',
        name: 'Thunderbolt Piercer',
        shortName: 'Thunder [3]',
        icon: '🔱',
        typeTag: 'THUNDER PIERCE',
        badgeClass: 'tag-piercing',
        pellets: 1,
        spread: 0.01,
        speed: 36,
        hullDmg: 175,
        sailDmg: 50,
        crewDmg: 50,
        color: '#0891b2',
        glow: '#22d3ee',
        pierce: 5,
        special: 'pierce',
        desc: 'Single piercing bolt of pure lightning that shoots right through up to 5 hulls and sails at hyper-speed.',
      },
    ],
  },
  {
    id: 7,
    name: 'Infernal Dread-Forge Cannon',
    price: 16000,
    desc: 'The ultimate legendary pirate weapon: an apocalyptic 6-gun barrage of cataclysmic fire!',
    damage: 8.0,
    reload: 280,
    range: 1150,
    spreadMod: 0.3,
    color: '#ef4444',
    volley: 6,
    bulletType: 'infernal',
    cursorStyle: 'infernal',
    icon: '👑',
    ammoModes: [
      {
        id: 'infernal_hellfire',
        name: 'Cataclysm Hellfire Salvo',
        shortName: 'Hellfire [1]',
        icon: '👑',
        typeTag: 'CATACLYSMIC',
        badgeClass: 'tag-cataclysmic',
        pellets: 1,
        spread: 0.04,
        speed: 25,
        hullDmg: 130,
        sailDmg: 50,
        crewDmg: 50,
        color: '#ef4444',
        glow: '#f87171',
        aoeRadius: 80,
        special: 'standard',
        desc: 'Apocalyptic hellfire shells that unleash secondary fire explosions.',
      },
      {
        id: 'infernal_dragon',
        name: 'Dragon Breath Shotgun',
        shortName: 'Dragon [2]',
        icon: '🔥',
        typeTag: 'HELLFIRE SHOTGUN',
        badgeClass: 'tag-shotgun',
        pellets: 12,
        spread: 0.32,
        speed: 20,
        range: 320,
        hullDmg: 35,
        sailDmg: 45,
        crewDmg: 60,
        color: '#f87171',
        glow: '#fca5a5',
        special: 'shotgun',
        desc: 'Devastating close-quarters 12-ember hellfire shotgun spray that incinerates everything in a wide arc up close.',
      },
      {
        id: 'infernal_demon',
        name: 'Demon-Core Piercer',
        shortName: 'Core Beam [3]',
        icon: '⚡',
        typeTag: 'EXPLOSIVE PIERCE',
        badgeClass: 'tag-piercing',
        pellets: 1,
        spread: 0.01,
        speed: 38,
        hullDmg: 220,
        sailDmg: 65,
        crewDmg: 65,
        color: '#b91c1c',
        glow: '#ef4444',
        pierce: 6,
        aoeRadius: 65,
        special: 'pierce',
        desc: 'Single cataclysmic demon laser core that pierces up to 6 ships, detonating AOE blasts on each!',
      },
    ],
  },
];

const ENEMY_TYPES = {
  sloop: {
    name: 'Royal Scout Sloop',
    hull: 60,
    sail: 50,
    crew: 30,
    speed: 3.9,
    turnRate: 0.045,
    damage: 8,
    fireRate: 2400,
    range: 360,
    score: 120,
    size: 22,
    color: '#1e3a8a',
    sailColor: '#ffffff',
    flagColor: '#dc2626',
    behavior: 'swarm',
  },
  corsair: {
    name: 'Corsair Raider',
    hull: 90,
    sail: 80,
    crew: 45,
    speed: 4.2,
    turnRate: 0.048,
    damage: 12,
    fireRate: 1900,
    range: 390,
    score: 220,
    size: 24,
    color: '#065f46',
    sailColor: '#a7f3d0',
    flagColor: '#10b981',
    behavior: 'flank',
  },
  sloopOfWar: {
    name: 'Royal Sloop-of-War',
    hull: 140,
    sail: 75,
    crew: 55,
    speed: 3.0,
    turnRate: 0.032,
    damage: 16,
    fireRate: 1900,
    range: 420,
    score: 300,
    size: 28,
    color: '#312e81',
    sailColor: '#e0e7ff',
    flagColor: '#1d4ed8',
    behavior: 'flank',
  },
  fireGalley: {
    name: 'Greek Fire Galley',
    hull: 170,
    sail: 60,
    crew: 50,
    speed: 3.2,
    turnRate: 0.038,
    damage: 22,
    fireRate: 1600,
    range: 360,
    score: 450,
    size: 30,
    color: '#9a3412',
    sailColor: '#fed7aa',
    flagColor: '#f97316',
    behavior: 'swarm',
    isFire: true,
  },
  bombKetch: {
    name: 'Siege Bomb Ketch',
    hull: 110,
    sail: 40,
    crew: 40,
    speed: 1.9,
    turnRate: 0.025,
    damage: 32,
    fireRate: 3600,
    range: 650,
    score: 400,
    size: 27,
    color: '#7f1d1d',
    sailColor: '#fecaca',
    flagColor: '#991b1b',
    behavior: 'siege',
    mortar: true,
  },
  phantomBrig: {
    name: 'Cursed Phantom Brig',
    hull: 230,
    sail: 110,
    crew: 70,
    speed: 3.5,
    turnRate: 0.04,
    damage: 25,
    fireRate: 1700,
    range: 460,
    score: 750,
    size: 33,
    color: '#134e4a',
    sailColor: '#2dd4bf',
    flagColor: '#14b8a6',
    behavior: 'flank',
    isGhost: true,
  },
  manOWar: {
    name: 'King\'s Man-o-War',
    hull: 380,
    sail: 110,
    crew: 90,
    speed: 2.2,
    turnRate: 0.02,
    damage: 28,
    fireRate: 1600,
    range: 480,
    score: 950,
    size: 42,
    color: '#1e293b',
    sailColor: '#f8fafc',
    flagColor: '#0f172a',
    behavior: 'advance',
    isMiniBoss: true,
  },
  ironclad: {
    name: 'Armored Ironclad Ram',
    hull: 580,
    sail: 90,
    crew: 100,
    speed: 2.6,
    turnRate: 0.022,
    damage: 35,
    fireRate: 2100,
    range: 410,
    score: 1400,
    size: 45,
    color: '#374151',
    sailColor: '#9ca3af',
    flagColor: '#4b5563',
    behavior: 'advance',
    isMiniBoss: true,
  },
  // BOSSES (Spawn on wave 5, 10, 15, 20, etc.)
  flagship: {
    name: 'HMS Sovereign (Imperial Flagship)',
    hull: 850,
    sail: 140,
    crew: 140,
    speed: 1.7,
    turnRate: 0.016,
    damage: 38,
    fireRate: 1300,
    range: 550,
    score: 2500,
    size: 58,
    color: '#422006',
    sailColor: '#fef3c7',
    flagColor: '#ca8a04',
    behavior: 'boss',
    isBoss: true,
  },
  dutchman: {
    name: 'The Flying Dutchman',
    hull: 1350,
    sail: 180,
    crew: 180,
    speed: 2.3,
    turnRate: 0.022,
    damage: 46,
    fireRate: 1150,
    range: 600,
    score: 5000,
    size: 64,
    color: '#022c22',
    sailColor: '#5eead4',
    flagColor: '#0d9488',
    behavior: 'boss',
    isBoss: true,
    isGhost: true,
  },
  leviathan: {
    name: 'Kraken-Bound Dreadnought',
    hull: 1950,
    sail: 210,
    crew: 220,
    speed: 1.9,
    turnRate: 0.018,
    damage: 56,
    fireRate: 1050,
    range: 650,
    score: 8000,
    size: 70,
    color: '#3b0764',
    sailColor: '#d8b4fe',
    flagColor: '#9333ea',
    behavior: 'boss',
    isBoss: true,
  },
  infernoBehemoth: {
    name: 'Infernal Leviathan Fortress',
    hull: 2800,
    sail: 250,
    crew: 280,
    speed: 1.8,
    turnRate: 0.016,
    damage: 72,
    fireRate: 900,
    range: 700,
    score: 13000,
    size: 76,
    color: '#450a0a',
    sailColor: '#fca5a5',
    flagColor: '#dc2626',
    behavior: 'boss',
    isBoss: true,
  },
};

const LEVELS = [
  {
    id: 0,
    name: 'Volcanic Lagoon',
    startWave: 1,
    waterDeep: '#0284c7',
    waterMid: '#0ea5e9',
    waterLight: '#38bdf8',
    foam: '#bae6fd',
    hazard: 'lava',
    hazardColor: '#ff4500',
    accent: '#fbbf24',
  },
  {
    id: 1,
    name: 'Stormy Shoals',
    startWave: 6,
    waterDeep: '#0f172a',
    waterMid: '#1e3a8a',
    waterLight: '#3b82f6',
    foam: '#bfdbfe',
    hazard: 'storm',
    hazardColor: '#94a3b8',
    accent: '#e2e8f0',
  },
  {
    id: 2,
    name: 'Coral Reef Atolls',
    startWave: 11,
    waterDeep: '#0f766e',
    waterMid: '#14b8a6',
    waterLight: '#2dd4bf',
    foam: '#99f6e4',
    hazard: 'reef',
    hazardColor: '#f97316',
    accent: '#fb923c',
  },
  {
    id: 3,
    name: 'King\'s Blockade',
    startWave: 16,
    waterDeep: '#18181b',
    waterMid: '#3f3f46',
    waterLight: '#71717a',
    foam: '#d4d4d8',
    hazard: 'blockade',
    hazardColor: '#78716c',
    accent: '#d6d3d1',
  },
  {
    id: 4,
    name: 'Inferno Cove',
    startWave: 21,
    waterDeep: '#450a0a',
    waterMid: '#991b1b',
    waterLight: '#ef4444',
    foam: '#fecaca',
    hazard: 'inferno',
    hazardColor: '#fbbf24',
    accent: '#fde047',
  },
];

const PLAYER = {
  maxHull: 100,
  maxSail: 100,
  maxCrew: 100,
  speed: 4.5,
  size: 32,
  repairAmount: 25,
  repairCooldown: 8000,
  repairDuration: 2000,
};

const COMBO_TIMEOUT = 3200;
const COMBO_MULTIPLIERS = [1, 1.5, 2, 2.5, 3, 4, 5, 7, 10];

const SHIP_UPGRADES_DEF = [
  {
    id: 'hull',
    name: 'Reinforced Ironwood Armor',
    icon: '🛡️',
    basePrice: 500,
    priceScale: 1.8,
    maxLevel: 5,
    desc: 'Bolsters hull plating against enemy cannon fire.',
    statPerLevel: '+25 Max Hull HP',
  },
  {
    id: 'sails',
    name: 'Silk-Weave Storm Rigging',
    icon: '⛵',
    basePrice: 450,
    priceScale: 1.7,
    maxLevel: 5,
    desc: 'Enhances sail efficiency for faster top speed and swift acceleration.',
    statPerLevel: '+12% Speed & Tailwind Boost',
  },
  {
    id: 'bunks',
    name: 'Expanded Crew Quarters',
    icon: '🛏️',
    basePrice: 400,
    priceScale: 1.6,
    maxLevel: 5,
    desc: 'More living space to house gunner crews, increasing reload rate.',
    statPerLevel: '+20 Max Crew & +10% Reload Speed',
  },
  {
    id: 'repair',
    name: 'High-Pressure Bilge Pumps',
    icon: '🔧',
    basePrice: 600,
    priceScale: 1.9,
    maxLevel: 5,
    desc: 'Improves field repair tools, reducing cooldown and restoring more health.',
    statPerLevel: '+10 Repair HP & -1s Cooldown',
  },
  {
    id: 'broadside',
    name: 'Port & Starboard Gun Batteries',
    icon: '💣',
    basePrice: 800,
    priceScale: 2.0,
    maxLevel: 5,
    desc: 'Mounts additional heavy cannon ports along the ship flanks.',
    statPerLevel: '+1 Gun per Flank & +15% Damage',
  },
];

const CREW_OFFICERS_DEF = [
  {
    id: 'captain',
    name: 'Captain Edward "Blackbeard"',
    role: 'Captain',
    icon: '👑',
    avatar: '🏴‍☠️',
    basePrice: 600,
    priceScale: 2.0,
    maxLevel: 5,
    traits: ['Feared Leader', 'Tactician'],
    desc: 'Inspires dread across the seven seas. Extends score combo timers and boosts doubloons earned.',
    perk: '+20% Combo Duration & +15% Score per level',
  },
  {
    id: 'gunner',
    name: 'Master Gunner Finnegan',
    role: 'Master Gunner',
    icon: '💣',
    avatar: '💥',
    basePrice: 500,
    priceScale: 1.8,
    maxLevel: 5,
    traits: ['Dead-Eye', 'Black Powder Master'],
    desc: 'Finely tunes powder mixtures and cannon sights for devastating firepower.',
    perk: '+15% All Cannon Damage per level',
  },
  {
    id: 'navigator',
    name: 'Helmsman Jack Drake',
    role: 'Navigator',
    icon: '🧭',
    avatar: '🗺️',
    basePrice: 450,
    priceScale: 1.7,
    maxLevel: 5,
    traits: ['Wind Whisperer', 'Sea Dog'],
    desc: 'Knows every current and wind pattern in the lagoon for sharper steering.',
    perk: '+18% Turning Speed & +10% Wind Surge per level',
  },
  {
    id: 'surgeon',
    name: 'Surgeon Bartholomew Hawkins',
    role: 'Ship Surgeon',
    icon: '🩺',
    avatar: '🩹',
    basePrice: 550,
    priceScale: 1.9,
    maxLevel: 5,
    traits: ['Herbalist', 'Field Medic'],
    desc: 'Tends to wounded sailors, providing continuous crew and hull regeneration.',
    perk: 'Regenerates 1 Crew & 0.6 Hull every 2 seconds per level',
  },
  {
    id: 'carpenter',
    name: 'Barnaby "Iron-Oak"',
    role: 'Chief Carpenter',
    icon: '⚓',
    avatar: '🪓',
    basePrice: 500,
    priceScale: 1.8,
    maxLevel: 5,
    traits: ['Shipwright', 'Salvager'],
    desc: 'Patches breaches on the fly and fortifies the keel against collisions.',
    perk: '-20% Collision Damage & +35% Repair Timber effectiveness per level',
  },
  {
    id: 'quartermaster',
    name: 'Quartermaster Silver-Tongue',
    role: 'Quartermaster',
    icon: '💰',
    avatar: '🪙',
    basePrice: 400,
    priceScale: 1.7,
    maxLevel: 5,
    traits: ['Smuggler', 'Treasure Hunter'],
    desc: 'Sniffs out hidden Spanish doubloons from every sunken enemy vessel.',
    perk: '+25% Doubloons found & +15% Loot Drop Rate per level',
  },
];

const PLAYABLE_SHIPS = [
  {
    id: 'black_pearl',
    name: 'The Black Pearl',
    title: 'Cursed Flagship',
    price: 0,
    desc: 'The legendary dark galleon of the Caribbean. Balanced speed, formidable armor, and dual-masted agility.',
    hull: 100,
    sail: 100,
    crew: 100,
    speed: 4.5,
    turnRate: 0.040,
    broadsideBonus: 0,
    masts: 2,
    size: 42,
    color: '#1b120c',
    deckColor: '#452b1a',
    sailColor: '#e2d9cc',
    trimColor: '#eab308',
    flagColor: '#0f0505',
    flagEmblem: '☠',
    icon: '🏴‍☠️',
    special: 'All-Rounder Caribbean Flagship',
  },
  {
    id: 'sea_dart',
    name: 'The Sea Dart',
    title: 'Corsair Cutter',
    price: 1500,
    desc: 'A swift, light cutter built for lightning raids. High acceleration and nimble helm, perfect for hit-and-run.',
    hull: 80,
    sail: 120,
    crew: 60,
    speed: 6.2,
    turnRate: 0.055,
    broadsideBonus: 0,
    masts: 1,
    size: 34,
    color: '#3b2014',
    deckColor: '#6e472a',
    sailColor: '#f8fafc',
    trimColor: '#38bdf8',
    flagColor: '#0284c7',
    flagEmblem: '⚡',
    icon: '⚡',
    special: '+35% Speed & Agile Rudder',
  },
  {
    id: 'iron_leviathan',
    name: 'The Iron Leviathan',
    title: 'Armored War Brig',
    price: 3500,
    desc: 'Reinforced with thick ironwood bulkheads and brass fittings. Slower, but withstands brutal punishment.',
    hull: 160,
    sail: 85,
    crew: 120,
    speed: 4.0,
    turnRate: 0.034,
    broadsideBonus: 1,
    masts: 2,
    size: 46,
    color: '#27272a',
    deckColor: '#3f3f46',
    sailColor: '#d4d4d8',
    trimColor: '#fbbf24',
    flagColor: '#713f12',
    flagEmblem: '🛡️',
    icon: '🛡️',
    special: '+60 Max HP & +1 Broadside Gun',
  },
  {
    id: 'queen_annes_revenge',
    name: "Queen Anne's Revenge",
    title: 'Cursed Phantom Galleon',
    price: 6500,
    desc: 'Wreathed in ghostly sea-mist with crimson sails. Possesses supernatural dread and enhanced broadside firepower.',
    hull: 190,
    sail: 105,
    crew: 140,
    speed: 4.9,
    turnRate: 0.038,
    broadsideBonus: 1,
    masts: 3,
    size: 50,
    color: '#18181b',
    deckColor: '#271b2d',
    sailColor: '#dc2626',
    trimColor: '#a855f7',
    flagColor: '#881337',
    flagEmblem: '🔥',
    icon: '👻',
    isGhost: true,
    special: 'Spectral Glow & +1 Broadside Gun',
  },
  {
    id: 'neptunes_colossus',
    name: "Neptune's Colossus",
    title: 'First-Rate Dreadnought',
    price: 10000,
    desc: 'The absolute undisputed sovereign of the ocean. Four soaring masts, colossal multi-deck hull, and quad broadside barrages.',
    hull: 240,
    sail: 110,
    crew: 180,
    speed: 4.4,
    turnRate: 0.030,
    broadsideBonus: 2,
    masts: 4,
    size: 56,
    color: '#0c192c',
    deckColor: '#1e293b',
    sailColor: '#f8fafc',
    trimColor: '#ffd700',
    flagColor: '#1e3a8a',
    flagEmblem: '🔱',
    icon: '🔱',
    special: '+140 Max HP & +2 Broadside Guns',
  },
];
